service: app-travels-clients-microservice

provider:
  name: aws
  stage: ${opt:stage, 'develop'}
  region: us-east-1
  runtime: nodejs18.x
  stackTags:
    MICROSERVICE: "clients-microservice"

custom:
  stage: ${self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
  prune:
    automatic: true
    number: 1

functions:
  - ${file(./sls/lambda/functions.yml)}

resources:
  - ${file(./sls/dynamo/users-table.yml)}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-resource-tagging
  - serverless-prune-plugin
  - serverless-iam-roles-per-function